### PR TITLE
VGA: Fix color expansion (666 to 888)

### PR DESCRIPTION
**Pull request by SimpleTease**

### CODE REVIEW

**Comment by frranck** [comment]
Hello, do you see any difference? What is the reasoning?

**Comment by frranck** [comment]
Untitled

**Comment by frranck** [comment]
OK we can see a small difference...

**Comment by frranck** [comment]
So this is less saturated?

**Comment by SimpleTease** [comment]
I've seen this "bug" several times in other projects. The concern is that the full color range is not being used. I've met enough who can notice these things.
```
11111100 = FC (max)
(111111)(11) = FF (max)

10000000 = 80 (mid)
(100000)(10) = 82 (mid)
```

It's very minor color change but I've dealt with other devs who told me to fix it the proper way. Mednafen author uses linear equations `(0-63) / 255`, which generates the same bitshift results for discussion.

Personally I don't care enough either way, but wanted to bring it up once.

**Comment by frranck** [comment]
thanks, nice catch

**Pull request merged**
