### PR TITLE
asm: program re-entry at vbl

### PR DESCRIPTION
**Pull request by SimpleTease**

### CODE REVIEW

**Comment by SimpleTease** [comment]
https://github.com/Javanaise/mrboom-libretro/blob/46f3a1699895fa0ddbdbcb6075c4cf077b3eca08/mrboom.c#L10796-L10804

```
 vblavbl2x353: 
 IN(READDBl(eax),READDW(edx)); 
==> m.nosetjmp = 2
==> exits program


 R(TEST(8,READDBl(eax),8,(db)8)); 
 R(JE(vblavbl2x353)); 

@@@  this gets skipped
 R(XOR(32,READDD(eax),32,(dd)READDD(eax))); 
 R(XOR(32,READDD(edx),32,(dd)READDD(edx))); 
@@@  this gets skipped


==> re-entry here
 directjeu: 
 CALL(master1); 
 trtyrtrtyrtyrtyrtyrtytyrrtyrtytyryrtrty: 
```

I saw this when using a debugger. A bunch of printfs can also verify this behavior.

**Comment by frranck** [comment]
its just setting eax and edx to 0, prob it's not getting used in master1

**Comment by frranck** [comment]
maybe fixing this https://github.com/Javanaise/mrboom-libretro/issues/36 would make more sense?

**Comment by SimpleTease** [comment]
> its just setting eax and edx to 0, prob it's not getting used in master1

Okay. Just checking to be safe.

> maybe fixing this #36 would make more sense?

I did check out the issue but don't have a Switch. And can't get Retroarch Emscripten to work on my machine... :grumpy_cat:

**Pull request closed without merging**
