### PR TITLE
Victory: Show whole team together on stage

### PR DESCRIPTION
**Pull request by SimpleTease**

### CODE REVIEW

**Comment by SimpleTease** [comment]
Surprisingly tricky and messy. But Supreme Victory shows whole team on stage, centered with some gap. What would be neat is to have a new bgm (or fanfare) for the finale instead of continuing the stage bgm.

**Comment by frranck** [comment]
indeed that's a serious hack :) 

therer's a warning

```
mrboom.c:1939:21: warning: cast to 'uint32_t *' (aka 'unsigned int *') from smaller integer type 'uint32_t'
      (aka 'unsigned int') [-Wint-to-pointer-cast]
victorySpriteBase = (dd*)(*(dd*)((db*)m.donnee + (8*2*3) + victoryPlayer*4));
                    ^
```

**Comment by frranck** [comment]
ps: did you notice there is a activeCheatMode function to test faster?

**Comment by frranck** [comment]
tested with 2 + 1 player in -s it worked

**Comment by frranck** [comment]
what do you mean bgm? send me an email will invite you on my slack.

**Comment by frranck** [comment]
do you think this would work? https://github.com/Javanaise/mrboom-libretro/commit/5f88ba2f9d6f28a52be5998be5966c742a7590ec I tried it once in -s

**Comment by SimpleTease** [comment]
> ps: did you notice there is a activeCheatMode function to test faster?

I saw it but never tried CheatMode yet. Changed rules to end game in 1 round. A selectable number would be an interesting feature; waiting for 5 rounds during normal play can get exhausting sometimes for quickie sessions.

> do you think this would work? 5f88ba2 I tried it once in -s

Tried https://github.com/Javanaise/mrboom-libretro/commit/5f88ba2f9d6f28a52be5998be5966c742a7590ec many times (2-8 players) and always worked correctly. All sprites visible and no glitches.

> what do you mean bgm? send me an email will invite you on my slack.

I use 10 minute disposable emails so everything gets ignored, and I'm not online often. By bgm, suggestion to play a new mod/xm music file for supreme victory. I haven't found an interesting track yet. Maybe also play an audience sfx for applause or cheering. But just thoughts.

**Pull request merged**
