### PR TITLE
msvc (2003,2005,2010,2017) targets

### PR DESCRIPTION
**Pull request by SimpleTease**

### CODE REVIEW

**Comment by SimpleTease** [comment]
Pending on PR https://github.com/libretro/libretro-common/pull/174. Afterwards it will compile and be marked ready for review. Did not test Xbox targets as I don't have access to those compilers.

**Comment by frranck** [comment]
Hi @SimpleTease, this is breaking the SDL2 versions:

```
sdl2/sdl2_data.h:91431:1: error: narrowing conversion of ‘208’ from ‘int’ to ‘char’ [-Wnarrowing]
sdl2/sdl2_data.h:91431:1: error: narrowing conversion of ‘240’ from ‘int’ to ‘char’ [-Wnarrowing]
sdl2/sdl2_data.h:91431:1: error: narrowing conversion of ‘164’ from ‘int’ to ‘char’ [-Wnarrowing]
sdl2/sdl2_data.h:91431:1: error: narrowing conversion of ‘129’ from ‘int’ to ‘char’ [-Wnarrowing]
sdl2/sdl2_data.h:91431:1: error: narrowing conversion of ‘206’ from ‘int’ to ‘char’ [-Wnarrowing]

```

**Comment by SimpleTease** [comment]
Oh bashful! I'll get back to you on this. :rofl:

**Comment by SimpleTease** [comment]
Tested gcc and narrowing should be flushed away.

**Comment by frranck** [comment]
you need to compile with
`make mrboom LIBSDL2=1`
it stills fails:
```
<built-in>: note: this is the location of the previous definition
make: *** No rule to make target 'libretro-common/time/rtime.o', needed by 'mrboom'.  Stop.
```

**Comment by frranck** [comment]
Did you try with  `make mrboom LIBSDL2=1` ?
Because it still fails 
```
<built-in>: note: this is the location of the previous definition
make: *** No rule to make target 'libretro-common/time/rtime.o', needed by 'mrboom'.  Stop.
```

**Comment by frranck** [comment]
I guess it's because you updated libretro-common.

**Comment by SimpleTease** [comment]
`make mrboom LIBSDL2=1`
Oops. Didn't realize that was the magic instruction.

Yeah.. unfortunately this PR is currently useless for merging because of the libretro-common. When I updated libretro-common to current https://github.com/libretro/libretro-common/commit/09ca0412247abb8bc527cb192c22507c70d237f6, `time/rtime.c` is now needed to build for the libretro file api.

But msvc 2003 still crashes because `retro_endianness.h` includes `winsock2.h` to detect compiler endianness. But turns out msvc already has predefined macros (_M_IX86, _M_AMD64, _M_ARM, _M_ARM64) for this and is not needed.
https://github.com/libretro/libretro-common/pull/174/files#diff-ba930bb5c1dca49bf870fdf229fc7098ad6fc94b39739a34cf71cc3725273053L84-L87

Then msvc 2010 x64 refused to build. Compiler does not natively predefine `__SSE2__` and we need someone to define it inside `audio/audio_mix.c`.
https://github.com/libretro/libretro-common/pull/174/files#diff-48110c16cd03f790669b7d29b4c220364b6d4aee7ffe32a5a133101cf422b222R28

If it ever gets accepted, then I can add to the MrBoom PR the updated submodule hotlink and mark it ready for merging.
```
git submodule update --init --recursive
git submodule update --remote --merge
git add .
```

But it's not whole and complete so I sit on it. Sorry for the hassle, didn't expect MSVC targets to be this much work. :annoyed:

**Comment by SimpleTease** [comment]
Warning: this will still break on some msvc targets but I'm no longer interested.

**Comment by SimpleTease** [comment]
Did clean pr test. All targets built and ready for buildbot. Can't say for Xbox though but I imagine should be similar. Be warned that 2010 x64 takes ~25 minutes to build.

**Comment by frranck** [comment]
make is giving me
`
ld: unknown option: -fPIC
`

**Comment by SimpleTease** [comment]
Oh no. :( Let me compare against my local checkout. I tested earlier with gcc 10.

**Comment by SimpleTease** [comment]
I'm hoping for no problems now??

**Comment by frranck** [comment]
seems fine, shall I merge?

**Comment by SimpleTease** [comment]
I see no problems on my end. I guess we won't know if buildbot barfs until the commit goes through.

**Pull request merged**
