### PR TITLE
Fixed Haiku linking with new network support

### PR DESCRIPTION
**Pull request by kwyxz**
The new network code was breaking Haiku build, this fixes it and will allow packaging. Thanks!

### CODE REVIEW

**Comment by frranck** [comment]
thanks

**Comment by frranck** [comment]
@kwyxz https://repology.org/metapackage/mrboom/versions lol

**Comment by kwyxz** [comment]
Haiku is bleeding edge B)


-- 
Le jeu vidéo des vieux bougons http://www.gamingsince198x.fr
Le podcast qui aime bien détester les trucs pas bien http://www.afterhate.fr

**Comment by frranck** [comment]
the AUR version has a version 4.5.r4.gc6e22e8 and it doesn't do that, could you please rename it to something similar?

**Comment by frranck** [comment]
prob 4.5.20181226 would work

**Comment by kwyxz** [comment]
I initially proposed the following form: 4.5~git20181226 but it was rejected by the Haiku maintainers, who imposed the current versioning :/

**Comment by frranck** [comment]
@kwyxz Hi! could you please update to 4.7?

**Pull request merged**
