### PR TITLE
AI: refactor search paths

### PR DESCRIPTION
**Pull request by SimpleTease**

### CODE REVIEW

**Comment by frranck** [comment]
so that's not different, that's a refactor is it?

**Comment by SimpleTease** [comment]
Didn't know that was the correct technical term. Fixed!

**Comment by frranck** [comment]
@SimpleTease FYI, I fixed the script to do the "statetests" that can be used as regression tests for the AI, so if I do that On branch SimpleTease-patch-11

```
git rebase master
tests/runTest.sh statetests
(...)
Sat Nov 14 07:09:25 CET 2020 test success 0 25
****
```

It will run the AI against itself and dump some states, It will check the paths are calculated the same, otherwise the states would be different. 
This change is changing the states, most likely it's simply a different order in decision and it would be working fine. But the problem is the AI has been tested a lot already and  I don't have time to test things that are working fine, there's no benefits in refactoring if we risk to introduce bugs.

**Comment by SimpleTease** [comment]
It lowers chance of bots doing same things by not using searching same paths. It's annoying when a group does that instead of possibly doing different things.

> This change is changing the states, most likely it's simply a different order in decision and it would be working fine. But the problem is the AI has been tested a lot already and I don't have time to test things that are working fine, there's no benefits in refactoring if we risk to introduce bugs.

Maybe it can be made into a switchable option for AI behavior.

All these PRs are suggestions and none are essential for the Mr.Boom community. I don't mind if any are closed.

**Comment by frranck** [comment]
That's interesting if it gets them not to do the same things, as long as it's deterministic, I added some salt somewhere already I think.

**Comment by SimpleTease** [comment]
Before it happened lots of times. Now it's more during "end-games" with powerful bots trapping each other in corners.

**Pull request merged**
