### PR TITLE
Helper: Workaround gcc 7.5.0 division bug

### PR DESCRIPTION
**Pull request by SimpleTease**
Avoid incorrect negative division optimization. Fixes bot behavior on Gamecube

### CODE REVIEW

**Comment by frranck** [comment]
that sounds very weird, there's no way to disable the optimisation flag? did you see it by viewing the assembly?

**Comment by frranck** [comment]
is it a known bug in gcc?

**Comment by frranck** [comment]
maybe add an #ifdef on GCC_VERSION ?

**Comment by SimpleTease** [comment]
I checked the output logs first, then some disasm. It's some carry flag optimization because of div 16, and it adds +1 to all negative divisions. But so far only on PPC arch it seems??
```
-7 to -6
..
-1 to -0
```

I know GCC can do some funny tricks. Snes9x ran into one about tree somethings. I remember that `x / -1` can get compiled into `neg x` on Intels but ARMs do straight div.

I'll look into the disabling flags. Never run into this exact one before. I've had some MSVC memory indexing errors that affected x86 but not x64.

**Comment by frranck** [comment]
ok thanks!

**Comment by SimpleTease** [comment]
I thought it was a compiler bug but it's an annoying PowerPC power-of-2 division optimization that rounds towards zero.

```
srawi     r6, r6, 4
addze     r6, r6
```

https://devblogs.microsoft.com/oldnewthing/20180810-00/?p=99465

> These four shift instructions are special because they always update carry: The carry bit is set if and only if the original value was negative and any bits shifted out were nonzero. This rule for the carry bit allows you to follow the right-shift instruction with an addze to perform a division by a power of two that rounds toward zero. (If you omit the addze, then the right shift performs a division by a power of two that rounds toward minus infinity.)

Maybe that explains why I see some libretro developers use bitshift division everywhere. Because of platforms like this one. So revisiting the code to make it more usable?

https://github.com/Javanaise/mrboom-libretro/blob/8c9dc9b6c18f304f8c7b3514e3e5f5f5524ff645/ai/MrboomHelper.hpp#L118-L122

I'd have to test on Gamecube but can't imagine why it'd break.

```
int inline getAdderX(int player)
{
#if CELLPIXELSSIZE == 16
   return(GETXPIXELSTOCENTEROFCELL(player) * framesToCrossACell(player) >> 4);
#else
   return(GETXPIXELSTOCENTEROFCELL(player) * framesToCrossACell(player) / CELLPIXELSSIZE);
#endif
}
```

**Comment by frranck** [comment]
yeah that would look better, also it's probably called a lot.

**Comment by CrystalBose** [comment]
@SimpleTease 
srawi + addze is normal correct division behavior. It's basically doing this
```
#define DIV(x,y) ((x >> y) + ((x < 0) && (x << (32 - y))))

-1 / 16 = 0
(-1 >> 4) = -1 (quotient)
(-1 < 0) && (-1 << (32 - 4)) = 1 && 1 = 1 (carry)
-1 + 1 = 0

-16 / 16 = -1
(-16 >> 4) = -1 (quotient)
(-16 < 0) && (-16 << (32 - 4)) = 1 && 0 = 0 (carry)
-1 + 0 = -1

-17 / 16 = -1
(-17 >> 4) = -2 (quotient)
(-17 < 0) && (-17 << (32 - 4)) = 1 && 1 = 1 (carry)
-2 + 1 = -1

-31 / 16 = -1
(-31 >> 4) = -2 (quotient)
(-31 < 0) && (-31 << (32 - 4)) = 1 && 1 = 1 (carry)
-2 + 1 = -1

-32 / 16 = -2
(-32 >> 4) = -2 (quotient)
(-32 < 0) && (-32 << (32 - 4)) = 1 && 0 = 0 (carry)
-2 + 0 = -2
```

We need to add that carry flag to get correct results. Using only a plain bitshift gives us wrong numbers.


Did this problem happen on an actual Gamecube or was it seen on Dolphin emulator? Because I tested on Dolphin.
- interpreter = okay
- JIT recompiler = okay
- JITIL recompiler = bad (carry problem?)

My opinion is the GCC compiler was generating correct PowerPC code and #79 can be safely reverted...........

**Comment by SimpleTease** [comment]
Not tested on real hardware. I believe you're right as PPC interpreter works with original math. And negative bitshift optimization does break on all platforms without the carry addition. I'll ask for revert. Sorry about that.

**Pull request merged**
