### PR TITLE
options: change skynet mode at round start

### PR DESCRIPTION
**Pull request by SimpleTease**

### CODE REVIEW

**Comment by SimpleTease** [comment]
Changing mode to Skynet in the middle of match ruins the rules and post-awards, as it takes affect immediately. Switching between any of the other 3 has no effect until next round begins.

This patch enforces that Skynet doesn't muck anything until after the medal screen.

**Comment by frranck** [comment]
I donno if your solution work, but I think the simplest way would be to only apply team changes when you are in the menu, because team settings were passed to the game using command line options.

**Comment by frranck** [comment]
also seems you're changing something for the replay, that could break the demo mode that happens a minute without touching anything.

**Comment by SimpleTease** [comment]
> I donno if your solution work, but I think the simplest way would be to only apply team changes when you are in the menu, because team settings were passed to the game using command line options.

Oh. Libretro currently let's you change rules between rounds. Doing in menu would solve a lot of problems, and be plenty easy.

**Comment by SimpleTease** [comment]
Switched to https://github.com/Javanaise/mrboom-libretro/pull/76

**Pull request closed without merging**
